# Dockerfile.download-car
ARG BASE_IMAGE=download-car-pro:latest
FROM ${BASE_IMAGE}

WORKDIR /download-car
COPY . .

RUN pip install --no-cache-dir matplotlib

ENTRYPOINT ["./entrypoint.download.sh"]
