# Dockerfile.api
ARG BASE_IMAGE=download-car-pro:latest
FROM ${BASE_IMAGE}

WORKDIR /download-car

COPY app.py /download-car/
COPY download_car/ /download-car/download_car/
COPY entrypoint.api.sh /download-car/

RUN chmod +x /download-car/entrypoint.api.sh

ENTRYPOINT ["/download-car/entrypoint.api.sh"]

